" Big Refactor still in progress.

"
"
" UTF-8
"

set encoding=utf-8

"
"
" Filetype & Syntax
"

filetype plugin indent on
syntax on

"
"
" Leaders
"

let g:mapleader=';'
let g:maplocalleader="'"

"
"
" Plugs
"

runtime plugs.vim
