" Big Refactor still in progress.

runtime settings.vim
runtime commands.vim
runtime mappings.vim

runtime plugs.vim

runtime colors.vim

if filereadable(glob('~/.local.vimrc')) 
    source ~/.local.vimrc
endif
