" if executable('gsi')
"     call neoterm#repl#set('gsi')
" elseif executable('chez')
"     call neoterm#repl#set('chez')
" elseif executable('bigloo')
"     call neoterm#repl#set('bigloo')
" elseif executable('gosh')
"     call neoterm#repl#set('gosh')
" elseif executable('gosh')
"     call neoterm#repl#set('gosh')
" elseif executable('csi')
"     call neoterm#repl#set('csi')
" elseif executable('guile')
"     call neoterm#repl#set('guile')
" endif

call neoterm#repl#set('')
